import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Sparkles,Brain,Map,Code2,BookOpen,Play,Send,ChevronRight,ChevronDown,CheckCircle2,Loader2,RefreshCw,ArrowLeft,Plus,Search,Sun,Moon,MessageSquare,ShieldCheck,Database,Users,Layers} from 'lucide-react';
import './style.css';

const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';
const initialIdea='Build a college hostel management app for students, wardens and admins. Students should manage rooms, raise complaints with photos, request leave, and view announcements.';
const emptyProject={idea:'',understanding:null,plan:null,app_definition:null,explanation:null,learning:null};

async function api(path,body){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||'Request failed');return d}
function usePersisted(){const [p,setP]=useState(()=>{try{return JSON.parse(localStorage.getItem('lunor-project'))||emptyProject}catch{return emptyProject}});useEffect(()=>localStorage.setItem('lunor-project',JSON.stringify(p)),[p]);return [p,setP]}
const asArray=(v)=>Array.isArray(v)?v:(v==null?[]:[v]);
const safeText=(v,fallback='')=>typeof v==='string'||typeof v==='number'?String(v):fallback;
class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={hasError:false,error:''}}static getDerivedStateFromError(e){return {hasError:true,error:e?.message||'Unexpected UI error'}}componentDidCatch(e){console.error('Lunor UI error:',e)}render(){if(this.state.hasError)return <div className="app dark"><main><section className="panel"><div className="empty"><div className="emptyicon"><Sparkles/></div><h2>This stage hit a UI error</h2><p>Your project data is safe. Go back to another stage and try again.</p><small>{this.state.error}</small><div className="actions"><button className="primary" onClick={()=>this.setState({hasError:false,error:''})}>Try again</button></div></div></section></main></div>;return this.props.children}}

function App(){const [project,setProject]=usePersisted();const [idea,setIdea]=useState(project.idea||'');const [stage,setStage]=useState(project.app_definition?'build':'understand');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [toast,setToast]=useState('');const [modify,setModify]=useState('');const [health,setHealth]=useState(null);const [dark,setDark]=useState(true);
 useEffect(()=>{fetch(API+'/api/health').then(r=>r.json()).then(setHealth).catch(()=>setHealth(null))},[]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)}},[toast]);
 const run=async(label,fn)=>{setLoading(true);setError('');try{const d=await fn();return d}catch(e){setError(e.message);return null}finally{setLoading(false)}};
 const understand=async()=>{if(!idea.trim())return setError('Enter an app idea first.');const d=await run('Understand',()=>api('/api/understand',{idea}));if(d){setProject(x=>({...x,idea,understanding:d}));setStage('understand');setToast('Requirements understood by AI')}};
 const plan=async()=>{const d=await run('Plan',()=>api('/api/plan',{project:{...project,idea:idea||project.idea}}));if(d){setProject(x=>({...x,plan:d}));setStage('plan');setToast('Technical plan generated')}};
 const build=async()=>{const d=await run('Build',()=>api('/api/build',{project:{...project,idea:idea||project.idea}}));if(d){setProject(x=>({...x,idea:idea||x.idea,app_definition:d}));setStage('build');setToast('AI-built app is ready')}};
 const explain=async()=>{const d=await run('Explain',()=>api('/api/explain',{project}));if(d){setProject(x=>({...x,explanation:d}));setStage('explain')}};
 const learn=async()=>{const d=await run('Learn',()=>api('/api/learn',{project}));if(d){setProject(x=>({...x,learning:d}));setStage('learn')}};
 const applyModify=async()=>{if(!modify.trim()||!project.app_definition)return;const old=project.app_definition;const d=await run('Modify',()=>api('/api/modify',{project,change:modify}));if(d){setProject(x=>({...x,app_definition:d}));setModify('');setToast('Change applied without replacing your app')}else setProject(x=>({...x,app_definition:old}))};
 const reset=()=>{if(confirm('Start a new project?')){localStorage.removeItem('lunor-project');setProject(emptyProject);setIdea('');setStage('understand')}};
 const nav=[['understand','Understand',Brain],['plan','Plan',Map],['build','Build',Code2],['explain','Explain',MessageSquare],['learn','Learn',BookOpen]];
 return <div className={dark?'app dark':'app'}><header><div className="brand"><div className="logo">L</div><div><b>Lunor</b><span>App Studio</span></div></div><div className="header-right"><span className={health?.ai_enabled?'status on':'status'}><i/> {health?.ai_enabled?'Ollama connected':'AI offline'}</span><button className="iconbtn" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="newbtn" onClick={reset}><Plus size={16}/> New</button></div></header>
 <main><section className="hero"><div><p className="eyebrow"><Sparkles size={14}/> AI-FIRST APP DEVELOPMENT</p><h1>Build it. <em>Understand it.</em> Learn it.</h1><p className="sub">A guided workspace that turns an app idea into a plan, a working prototype, and a learning path — with Ollama + Llama 3.</p></div></section>
 <section className="workspace"><aside><div className="idea-box"><label>YOUR APP IDEA</label><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Describe the app you want to build..."/><button className="primary" disabled={loading} onClick={understand}>{loading?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>} Understand idea <ChevronRight size={16}/></button></div><div className="flow">{nav.map(([id,name,Icon],i)=><button key={id} className={stage===id?'nav active':'nav'} onClick={()=>setStage(id)}><span className="num">{i+1}</span><Icon size={17}/><span>{name}</span>{(id==='understand'&&project.understanding)||(id==='plan'&&project.plan)||(id==='build'&&project.app_definition)||(id==='explain'&&project.explanation)||(id==='learn'&&project.learning)?<CheckCircle2 size={14} className="done"/>:null}</button>)}</div><div className="pipeline"><div><b>Prompt → Understand → Plan</b><small>Build → Explain → Learn</small></div><Layers size={20}/></div></aside>
 <section className="panel">{error&&<div className="error">{error}<button onClick={()=>setError('')}>×</button></div>}{loading&&<div className="loading"><Loader2 className="spin" size={19}/> Llama 3 is working…</div>}{stage==='understand'&&<Understand data={project.understanding} onPlan={plan} onBuild={build}/>} {stage==='plan'&&<Plan data={project.plan} onBuild={build} onRefresh={plan}/>} {stage==='build'&&<Build app={project.app_definition} modify={modify} setModify={setModify} onModify={applyModify} onExplain={explain} onLearn={learn} toast={setToast}/>} {stage==='explain'&&<Explain data={project.explanation} onLearn={learn}/>} {stage==='learn'&&<Learn data={project.learning} onRegenerate={learn}/>}</section></section></main>{toast&&<div className="toast">✓ {toast}</div>}</div>}

function Empty({title,desc,action}){return <div className="empty"><div className="emptyicon"><Sparkles/></div><h2>{title}</h2><p>{desc}</p>{action}</div>}
function Understand({data,onPlan,onBuild}){const [open,setOpen]=useState(null);const users=asArray(data?.users).filter(x=>x&&typeof x==='object');const features=asArray(data?.features).filter(x=>x&&typeof x==='object');const questions=asArray(data?.questions).filter(x=>x&&typeof x==='object');if(!data)return <Empty title="Let's understand your idea" desc="The AI will identify users, core features, assumptions and the questions worth answering before any code is generated." action={<div className="actions"><button className="primary" onClick={onPlan}>Generate technical plan <ChevronRight size={16}/></button></div>}/>;return <div><Top title="Understand" sub="AI has turned your idea into product requirements."/><div className="grid2"><InfoCard icon={<Users/>} title="Users & goals">{users.map((u,i)=><button className="detail" key={i} onClick={()=>setOpen(open===i?null:i)}><b>{safeText(u.role,`User ${i+1}`)}</b><span>{asArray(u.goals).map(safeText).join(' · ')}</span>{open===i&&<small>Design around these goals instead of adding unrelated features.</small>}</button>)}</InfoCard><InfoCard icon={<Sparkles/>} title="Core features">{features.map((f,i)=><button className="detail" key={i} onClick={()=>setOpen(open===10+i?null:10+i)}><b>{safeText(f.name,`Feature ${i+1}`)} <label>{safeText(f.priority)}</label></b><span>{safeText(f.purpose)}</span>{open===10+i&&<small>This becomes a concrete screen/component during planning.</small>}</button>)}</InfoCard></div><InfoCard icon={<Brain/>} title="Questions before building"><div className="questions">{questions.map((q,i)=><label key={i}><input type="checkbox"/> <span><b>{safeText(q.question,`Question ${i+1}`)}</b><small>{safeText(q.why)}</small></span></label>)}</div></InfoCard><div className="actions"><button className="primary" onClick={onPlan}>Plan the architecture <ChevronRight size={16}/></button><button className="secondary" onClick={onBuild}>Skip to AI build</button></div></div>}
function Plan({data,onBuild,onRefresh}){const stack=asArray(data?.stack).filter(x=>x&&typeof x==='object');const screens=asArray(data?.screens).filter(x=>x&&typeof x==='object');const models=asArray(data?.data_model).filter(x=>x&&typeof x==='object');const security=asArray(data?.security).map(safeText).filter(Boolean);const why=asArray(data?.why_this_plan).map(safeText).filter(Boolean);if(!data)return <Empty title="Your technical plan will appear here" desc="Generate the plan after understanding the idea. It will cover stack, screens, data, architecture and security." action={<button className="primary" onClick={onRefresh}>Generate plan</button>}/>;const stackTitle=stack.slice(0,3).map(x=>safeText(x.technology)).filter(Boolean).join(' + ')||'Project stack';return <div><Top title="Plan" sub="A project-specific architecture generated by Llama 3."/><div className="planhero"><div><span className="pill">RECOMMENDED STACK</span><h2>{stackTitle}</h2><p>Optimized for a student-friendly prototype that can grow into a real mobile app.</p></div><Map size={34}/></div><div className="grid2"><InfoCard icon={<Code2/>} title="Stack">{stack.map((x,i)=><button className="detail" key={i}><b>{safeText(x.technology,`Technology ${i+1}`)}</b><span>{safeText(x.reason)}</span></button>)}</InfoCard><InfoCard icon={<Layers/>} title="Screens">{screens.map((x,i)=><button className="detail" key={i}><b>{safeText(x.name,`Screen ${i+1}`)}</b><span>{safeText(x.purpose)}</span></button>)}</InfoCard><InfoCard icon={<Database/>} title="Data model">{models.map((x,i)=><button className="detail" key={i}><b>{safeText(x.entity,`Entity ${i+1}`)}</b><span>{asArray(x.fields).map(safeText).join(' · ')}</span></button>)}</InfoCard><InfoCard icon={<ShieldCheck/>} title="Security">{security.map((x,i)=><div className="bullet" key={i}>✓ {x}</div>)}</InfoCard></div><InfoCard icon={<Map/>} title="Why this plan?"><div className="why">{why.map((x,i)=><p key={i}><span>{i+1}</span>{x}</p>)}</div></InfoCard><div className="actions"><button className="primary" onClick={onBuild}>Build this app <Play size={16}/></button><button className="secondary" onClick={onRefresh}><RefreshCw size={16}/> Regenerate plan</button></div></div>}
function Build({app,modify,setModify,onModify,onExplain,onLearn,toast}){if(!app)return <Empty title="Your AI-built app will appear here" desc="Use Understand or Plan first, then ask Llama 3 to build the actual prototype from your requirements."/>;const [screen,setScreen]=useState(0);const [dark,setDark]=useState(app.theme?.dark!==false);const [search,setSearch]=useState('');const [form,setForm]=useState({});const screens=app.screens||[];const current=screens[screen]||screens[0];const act=(a)=>{if(!a)return toast('Component ready');if(a.startsWith('navigate:')){const n=a.slice(9);const idx=screens.findIndex(s=>s.name.toLowerCase()===n.toLowerCase());if(idx>=0)setScreen(idx);else toast('Navigation target not found')}else if(a.startsWith('toast:'))toast(a.slice(6));else if(a.startsWith('toggle:'))setDark(v=>!v);else if(a.startsWith('submit:'))toast('Submitted successfully')};return <div><Top title="Build" sub="This preview is rendered from the AI-generated app definition — not a canned template."/><div className="builder"><div className="phonewrap"><div className={dark?'phone darkphone':'phone'}><div className="phonehead"><b>{app.app_name}</b><button onClick={()=>setDark(v=>!v)}>{dark?<Sun size={14}/>:<Moon size={14}/>}</button></div><div className="phonestatus">9:41 <span>●●●</span></div><div className="mobilecontent"><h2>{current.title}</h2><p className="mobiletag">{app.tagline}</p>{current.components.map((c,i)=><MobileComponent key={i} c={c} search={search} setSearch={setSearch} form={form} setForm={setForm} act={act}/>)}</div><div className="bottomnav">{screens.slice(0,4).map((s,i)=><button key={s.name} className={i===screen?'sel':''} onClick={()=>setScreen(i)}>{s.name.slice(0,8)}</button>)}</div></div></div><div className="buildside"><div className="change"><label>MODIFY WITH AI</label><div className="modifyrow"><input value={modify} onChange={e=>setModify(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onModify()} placeholder="e.g. Add dark mode to the dashboard"/><button onClick={onModify} disabled={!modify.trim()}><Send size={16}/></button></div><div className="chips"><button onClick={()=>setModify('Add dark mode')}>Add dark mode</button><button onClick={()=>setModify('Add photo upload to complaints')}>Add photo upload</button><button onClick={()=>setModify('Add a notifications screen')}>Add notifications</button></div></div><div className="buildcards"><button onClick={onExplain}><MessageSquare/><span><b>Explain my app</b><small>Understand the architecture and generated features.</small></span><ChevronRight/></button><button onClick={onLearn}><BookOpen/><span><b>Learn what I used</b><small>Get a project-specific learning path.</small></span><ChevronRight/></button></div><div className="ai-note"><Sparkles size={17}/><span><b>AI-built, not hardcoded.</b><small>Try a different idea — the screens and content will change with it.</small></span></div></div></div></div>}
function MobileComponent({c,search,setSearch,form,setForm,act}){if(c.type==='stat')return <div className="mstat"><small>{c.label}</small><b>{c.value}</b></div>;if(c.type==='announcement')return <button className="mann" onClick={()=>act(c.action)}><b>{c.label}</b><span>{c.value}</span></button>;if(c.type==='card')return <button className="mcard" onClick={()=>act(c.action)}><b>{c.label}</b><span>{c.value}</span></button>;if(c.type==='text')return <p className="mtext">{c.value||c.label}</p>;if(c.type==='image')return <div className="mimage">{c.label||'Photo area'}</div>;if(c.type==='toggle')return <button className="mtoggle" onClick={()=>act(c.action)}><span>{c.label}</span><i/></button>;if(c.type==='list')return <div className="mlist"><div className="search"><Search size={13}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/></div>{(search?(c.items||[]).filter(x=>x.toLowerCase().includes(search.toLowerCase())):(c.items||[])).map((x,i)=><button key={i} onClick={()=>act(c.action)}><span>•</span>{x}</button>)}</div>;if(c.type==='form')return <div className="mform">{(c.fields||[]).map(f=><input key={f.name} placeholder={f.label} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})}/>)}<button onClick={()=>act(c.action||'submit:form')}>{c.label||'Submit'}</button></div>;return <button className="mbutton" onClick={()=>act(c.action)}>{c.label||'Continue'}<ChevronRight size={14}/></button>}
function Explain({data,onLearn}){if(!data)return <Empty title="Explain the app" desc="Build the app first, then get a project-aware walkthrough."/>;return <div><Top title="Explain" sub="Learn why the generated app is structured the way it is."/><InfoCard icon={<Layers/>} title="Architecture">{data.architecture?.map((x,i)=><button className="detail" key={i}><b>{x.part}</b><span>{x.explanation}</span></button>)}</InfoCard><InfoCard icon={<Code2/>} title="Screen walkthrough">{data.screen_walkthrough?.map((x,i)=><button className="detail" key={i}><b>{x.screen}</b><span>{x.explanation}</span></button>)}</InfoCard><div className="grid2"><InfoCard icon={<Brain/>} title="Key concepts">{data.key_concepts?.map((x,i)=><div className="bullet" key={i}><b>{x.concept}:</b> {x.explanation}</div>)}</InfoCard><InfoCard icon={<ChevronRight/>} title="Next steps">{data.next_steps?.map((x,i)=><div className="bullet" key={i}>{i+1}. {x}</div>)}</InfoCard></div><div className="actions"><button className="primary" onClick={onLearn}>Turn this into a learning path <BookOpen size={16}/></button></div></div>}
function Learn({data,onRegenerate}){const [open,setOpen]=useState(null);const [done,setDone]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('lunor-lessons')||'[]');return Array.isArray(v)?v:[]}catch{return []}});const lessons=asArray(data?.lessons).filter(x=>x&&typeof x==='object');const resources=asArray(data?.resources).filter(x=>x&&typeof x==='object');if(!data)return <Empty title="Learn from your project" desc="Generate a project-specific learning path from the technologies and features you actually used." action={<button className="primary" onClick={onRegenerate}>Generate learning path</button>}/>;const toggle=(id)=>{const n=done.includes(id)?done.filter(x=>x!==id):[...done,id];setDone(n);localStorage.setItem('lunor-lessons',JSON.stringify(n))};return <div><Top title="Learn" sub="A small curriculum built from your actual project — not a generic course list."/><div className="progress"><div><b>{done.length}/{lessons.length}</b><span> lessons completed</span></div><div className="bar"><i style={{width:`${Math.min(100,(done.length/(lessons.length||1))*100)}%`}}/></div></div><div className="lessons">{lessons.map((l,i)=>{const id=safeText(l.id,`lesson-${i}`);const topics=asArray(l.topics).map(safeText).filter(Boolean);return <div className={open===id?'lesson open':'lesson'} key={id}><button className="lessonhead" onClick={()=>setOpen(open===id?null:id)}><span className={done.includes(id)?'check checked':'check'} onClick={e=>{e.stopPropagation();toggle(id)}}>{done.includes(id)?'✓':i+1}</span><span><small>{safeText(l.level,'CORE')}</small><b>{safeText(l.title,`Lesson ${i+1}`)}</b></span>{open===id?<ChevronDown/>:<ChevronRight/>}</button>{open===id&&<div className="lessonbody"><p>{safeText(l.why,'Learn this concept through the current project.')}</p><b>Topics</b><div className="topicrow">{topics.map(t=><span key={t}>{t}</span>)}</div><div className="practice"><Sparkles size={16}/><span><b>Practice</b><small>{safeText(l.practice,'Apply this concept to one part of your app.')}</small></span></div></div>}</div>})}</div><InfoCard icon={<BookOpen/>} title="Resources">{resources.map((r,i)=><div className="resource" key={i}><b>{safeText(r.title,`Resource ${i+1}`)}</b><span>{safeText(r.type,'Guide')} · {safeText(r.why)}</span></div>)}</InfoCard><InfoCard icon={<Play/>} title="Project challenge"><p>{safeText(data.project_challenge,'Build one additional feature using what you learned.')}</p><small>Estimated time: {safeText(data.estimated_hours,'—')} hours</small></InfoCard><button className="secondary" onClick={onRegenerate}><RefreshCw size={15}/> Regenerate learning path</button></div>}
function Top({title,sub}){return <div className="top"><div><p className="eyebrow">WORKSPACE STAGE</p><h2>{title}</h2><p>{sub}</p></div><div className="stagebadge"><Sparkles size={14}/> Llama 3</div></div>}
function InfoCard({icon,title,children}){return <section className="card"><div className="cardtitle">{icon}<h3>{title}</h3></div>{children}</section>}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
